extends "res://tests/mw019/行动推荐纵向测试.gd"

const Observer := preload("res://src/调试观测/L3_外交层/会话调试观测公开接口.gd")
var observer: Node

func _run() -> void:
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--root="): directory = arg.trim_prefix("--root=")
	if not directory.contains("mw022"):
		quit(2)
		return
	DirAccess.make_dir_recursive_absolute(directory)
	runtime = Runtime.new()
	check(runtime.open_current_game(directory.path_join("debug.sqlite")).success, "isolated SQLite")
	check(runtime.commit_world_mutation_durably("setup", "setup-node", setup()).success, "private fixture")
	observer = Observer.new(runtime)
	root.add_child(observer)
	semantic = Stub.new()
	worker = World.new(runtime, semantic)
	observer.observe_world(worker)
	root.add_child(worker)
	curation = Stub.new()
	curator = Curator.new(runtime, curation, worker)
	observer.observe_curator(curator)
	root.add_child(curator)
	recommendation = Stub.new()
	recommender = Recommender.new(runtime, recommendation)
	observer.observe_recommender(recommender)
	root.add_child(recommender)
	await frames()
	check(row("recommendations", -1).code == "input_unavailable" and recommendation.requests.is_empty(), "empty opportunity diagnostic without call")
	complete(curation, {"character": Safe.project_session(runtime).character, "experiences": []})
	await frames()
	accept("我停下休息。", "雨停了，你在亭中休息。")
	check(row("narrative", 0).terminal == "accepted" and row("world", 0).is_empty(), "accepted Narrative arrives before background")
	await frames()
	check(semantic.busy and not curation.busy and recommendation.busy, "existing asynchronous lane ordering")
	complete(semantic, {"changes": []})
	check(row("world", 0).change == "no-change" and row("identity", 0).change == "no-change", "World and Identity legitimate no-change")
	check(row("character", 0).is_empty(), "Curator still pending, no fake completion")
	await frames()
	complete(curation, answer([]))
	for lane: String in ["character", "experiences", "people"]:
		check(row(lane, 0).change == "no-change" and row(lane, 0).terminal == "committed", "safe no-change " + lane)
	complete(recommendation, {"actions": ACTIONS})
	check(row("recommendations", 0).terminal == "ready", "seven genuine lane results aggregate")
	check(semantic.requests.size() == 1 and curation.requests.size() == 2 and recommendation.requests.size() == 1, "observation adds zero calls")
	write_snapshot("ordinary.json")
	var immutable := durable()
	var copied: Array = observer.snapshot()
	copied[0].reason = "MUTATED"
	check(not JSON.stringify(observer.snapshot()).contains("MUTATED") and durable() == immutable, "snapshot detached and read-only")
	var save: Dictionary = runtime.create_save_point("ordinary")
	observer.record_operation("save", save)
	check(row("save", -1).terminal == "saved", "real Save result")
	accept("我接受沈青的邀请，从此随他行船。", "沈青答应带你渡河，你决定成为船工。")
	await frames()
	complete(semantic, {"changes": ["HIDDEN_WORLD_CANARY"], "new_actor_candidates": [{"candidate_ref": "new", "display_name": "沈青", "profile_text": "PRIVATE_PROFILE_CANARY"}], "people_bindings": [{"candidate_ref": "new", "gm_span": {"start": 0, "length": 2}}]})
	await frames()
	check(row("world", 1).change == "changed" and row("world", 1).counts.changes == 1, "World structural positive")
	check(row("identity", 1).counts == {"actors": 1, "bindings": 1}, "same transaction new actor and binding counts")
	var current_input := input()
	var reply := answer([{ "actor_ref": current_input.people_evidence[0].actor_ref, "snapshot": person("沈青", "船工", "邀请你同行。") }])
	reply.character = {"headline": "船工", "summary": "开始水上生涯", "groups": []}
	reply.experiences = [{"title": "成为船工", "description": "选择随船生活，开始新的人生道路。"}]
	complete(curation, reply)
	complete(recommendation, {"actions": ACTIONS})
	for lane: String in ["character", "experiences", "people"]: check(row(lane, 1).change == "changed", "safe positive " + lane)
	check(row("experiences", 1).counts.added == 1 and row("people", 1).counts.total == 1, "safe counts")
	write_snapshot("positive.json")
	# 非安全 prose 即使存在于真实 durable fixture / terminal 附加字段也不能流入展示。
	var extra: Dictionary = worker.status_snapshot()
	extra["raw"] = "Authorization SECRET_KEY SOURCE_CURRENT CANARY"
	worker.opportunity_terminal.emit(extra)
	privacy()
	accept("继续行走。", "你沿河走。")
	await frames()
	semantic.simulate_failed()
	await frames()
	curation.simulate_failed("Authorization SECRET_KEY")
	recommendation.simulate_delta("```json\n{}\n```")
	recommendation.simulate_completed()
	check(row("world", 2).terminal == "failed" and row("world", 2).change == "unknown", "failure distinct from no-change")
	for lane: String in ["character", "experiences", "people"]:
		check(row(lane, 2).terminal == "failed" and row(lane, 2).code == "provider_failure", "shared Curator failure " + lane)
	check(row("recommendations", 2).code == "malformed_response" and recommender.snapshot().status == "unavailable", "strict fence rejection, diagnostic-only reason")
	write_snapshot("failures.json")
	for mode: String in ["provider_failure", "cancelled", "timeout", "sync", "response_oversized", "stale"]:
		recommendation.synchronous_failure = mode == "sync"
		accept("行动 " + mode, "已接受的叙事 " + mode)
		await frames()
		var index: int = runtime.conversation.get_durable_accepted_entries().size() - 1
		var before := durable()
		if mode == "provider_failure": recommendation.simulate_failed("SECRET_KEY")
		elif mode == "cancelled": recommendation.cancel()
		elif mode == "timeout":
			recommender._timer.start(0.01)
			await create_timer(0.05).timeout
		elif mode == "response_oversized": recommendation.simulate_delta("x".repeat(RecommendationContract.RESPONSE_BYTES + 1))
		elif mode == "stale": recommender.interrupt_foreground()
		check(row("recommendations", index).code == ("provider_failure" if mode == "sync" else mode), "distinct recommendation " + mode)
		check(durable() == before and recommender.snapshot().actions.is_empty(), "fail-soft no durable write " + mode)
		complete(semantic, {"changes": []})
		await frames()
		complete(curation, answer([]))
		await frames()
		recommender._timer.wait_time = 120.0
	recommendation.synchronous_failure = false
	accept("即将被替换", "旧未来")
	await frames()
	var old_world: Dictionary = worker._active.duplicate(true)
	var old_delta: Callable = recommender._callbacks.text_delta
	var old_done: Callable = recommender._callbacks.completed
	complete(semantic, {"changes": []})
	await frames()
	var old_curation: Dictionary = curator._diagnostic_context.duplicate()
	var old_recommendation: Dictionary = recommender._diagnostic_context.duplicate()
	check(runtime.restore_save_point(save.save_id).success, "real Restore")
	check(observer.snapshot().size() == 1 and row("restore", -1).terminal == "restored", "Restore clears old epoch synchronously")
	old_world.merge({"success": true, "status": "committed", "change_count": 9}, true)
	worker.opportunity_terminal.emit(old_world)
	old_curation.merge({"success": true, "status": "committed"})
	curator.diagnostic_terminal.emit(old_curation)
	old_recommendation.merge({"terminal": "ready", "status": "ready"})
	recommender.diagnostic_terminal.emit(old_recommendation)
	old_delta.call(JSON.stringify({"actions": ACTIONS}))
	old_done.call()
	check(observer.snapshot().size() == 1, "late World/Curator/recommendation diagnostics cannot cross Restore")
	write_snapshot("restored.json")
	await frames()
	complete(recommendation, {"actions": ACTIONS})
	check(row("recommendations", 0).terminal == "ready", "new epoch valid request works")
	# 相同 accepted bytes 的真实 Restore 仍清 epoch。
	var same_save: Dictionary = runtime.create_save_point("same")
	var changed_world: Dictionary = runtime.world_state.duplicate(true)
	changed_world["private_fixture"] = "SOURCE_CURRENT"
	runtime.commit_world_mutation_durably("private", "private-node", changed_world)
	check(runtime.restore_save_point(same_save.save_id).success, "same accepted history Restore")
	check(observer.snapshot().size() == 1, "identical text does not bypass epoch boundary")
	await frames()
	complete(recommendation, {"actions": ACTIONS})
	runtime.conversation.retry_or_regenerate_latest()
	runtime.conversation.append_delta("替换后的当前叙事")
	check(runtime.complete_active_generation_durably().success, "accepted Regenerate")
	check(row("recommendations", 0).is_empty() and row("narrative", 0).terminal == "accepted", "old accepted-version rows pruned")
	await frames()
	complete(semantic, {"changes": []})
	await frames()
	complete(curation, answer([]))
	complete(recommendation, {"actions": ACTIONS})
	# 使用保存的旧 context 验证 replacement 丢弃，不靠 UI 原文推断。
	worker.opportunity_terminal.emit(old_world)
	check(row("world", 0).change == "no-change", "old world callback cannot overwrite replacement")
	accept("替换中的行动", "替换前的未来")
	await frames()
	complete(semantic, {"changes": []})
	await frames()
	old_curation = curator._diagnostic_context.duplicate()
	old_recommendation = recommender._diagnostic_context.duplicate()
	var current_world: Dictionary = worker.status_snapshot()
	runtime.conversation.retry_or_regenerate_latest()
	runtime.conversation.append_delta("同 epoch 的新版本")
	check(runtime.complete_active_generation_durably().success, "same epoch accepted replacement")
	check(row("world", 1).is_empty() and row("recommendations", 1).is_empty(), "replacement prunes displaced rows immediately")
	await frames()
	complete(curation, answer([]))
	check(row("character", 1).is_empty() and row("character", -1).terminal == "stale", "real stale Curator terminal remains stale, never new-version success")
	worker.opportunity_terminal.emit(current_world)
	check(row("world", 1).is_empty(), "same epoch old World prefix rejected")
	complete(semantic, {"changes": []})
	await frames()
	old_curation.merge({"success": true, "status": "committed"})
	curator.diagnostic_terminal.emit(old_curation)
	old_recommendation.merge({"terminal": "ready", "status": "ready"})
	recommender.diagnostic_terminal.emit(old_recommendation)
	check(row("character", 1).is_empty() and row("recommendations", 1).is_empty(), "old diagnostic callbacks cannot complete current replacement")
	complete(curation, answer([]))
	complete(recommendation, {"actions": ACTIONS})
	check(row("character", 1).terminal == "committed" and row("recommendations", 1).terminal == "ready", "replacement real terminals publish")
	# 历史复用 seam 无本次 transaction count；不能伪造 no-change。
	worker.consider_latest_accepted_turn()
	check(row("world", 1).change == "unknown" and row("identity", 1).counts.is_empty(), "historical terminal absent counts remain unknown")
	accept("超出推荐输入预算", "字".repeat(RecommendationContract.INPUT_BYTES))
	await frames()
	check(row("recommendations", 2).code == "input_unavailable" and not recommendation.busy, "oversized latest input no call / unavailable")
	semantic.simulate_failed()
	await frames()
	curation.simulate_failed()
	runtime.conversation.begin_turn("主动取消")
	runtime.conversation.cancel_generation()
	check(row("narrative", -1).terminal == "cancelled", "Narrative cancellation")
	runtime.conversation.retry_or_regenerate_latest()
	runtime.conversation.fail_generation("Authorization SECRET_KEY")
	check(row("narrative", -1).terminal == "failed" and row("narrative", -1).code == "unknown_failure", "unknown Narrative failure code sanitized")
	observer.record_operation("restore", {"success": true, "status": "already_current"})
	check(row("restore", -1).reason == "已处于所选进度", "already-current does not claim cleared epoch")
	immutable = durable()
	for i: int in range(80): observer.record_operation("save", {"success": false, "message": "SECRET_KEY C:/PRIVATE/path", "status": "RAW_RESPONSE"})
	check(observer.snapshot().size() == 64 and durable() == immutable, "64 bound; synthetic failure observation is read-only")
	check(row("save", -1).reason == "持久化失败", "safe human-readable operation failure")
	privacy()
	var evidence := FileAccess.open(directory.path_join("diagnostics.json"), FileAccess.WRITE)
	evidence.store_string(JSON.stringify(observer.snapshot(), "  "))
	evidence.close()
	observer.shutdown()
	check(observer.snapshot().is_empty(), "close discards entire buffer")
	observer.queue_free()
	detach()
	teardown()
	runtime.close()
	await frames()
	print("MW-022 FOCUSED checks=%d failures=%d" % [checks, failures])
	quit(0 if failures == 0 else 1)

func row(lane: String, turn: int) -> Dictionary:
	var rows: Array = observer.snapshot()
	for i: int in range(rows.size() - 1, -1, -1):
		if rows[i].lane == lane and rows[i].turn == turn: return rows[i]
	return {}

func durable() -> Dictionary:
	return {"head": runtime.active_head_id, "world": runtime.world_state.duplicate(true), "entries": runtime.conversation.get_durable_accepted_entries(), "nodes": runtime.persistence.timeline_node_count(runtime.game_id)}

func privacy() -> void:
	var text := JSON.stringify(observer.snapshot())
	for canary: String in ["SECRET_PROFILE", "PRIVATE_PLAN", "HIDDEN_EVOLUTION", "HIDDEN_WORLD_CANARY", "PRIVATE_PROFILE_CANARY", "SECRET_KEY", "Authorization", "SOURCE_CURRENT", "npc-a", "actor_ref", "prefix", "epoch", "raw", "船工", "沈青", "C:/PRIVATE"]:
		check(not text.contains(canary), "projection excludes " + canary)

func check(condition: bool, label: String) -> void:
	checks += 1
	if not condition:
		failures += 1
		push_error("MW-022 FAIL " + label)
	else: print("MW-022 PASS " + label)

func write_snapshot(name: String) -> void:
	var file := FileAccess.open(directory.path_join(name), FileAccess.WRITE)
	file.store_string(JSON.stringify(observer.snapshot(), "  "))
	file.close()
