extends "res://tests/mw014/模型信息整理纵向测试.gd"

const Contract := preload("res://src/信息整理/L0_公理层/信息整理契约.gd")
const Profile := preload("res://src/rpg视图模型/L3_外交层/RPG主机视图模型公开接口.gd")
const BASELINE := {"character": {"headline": "现代来客", "summary": "学习适应汉末的人。", "groups": [
	{"title": "出身 / 来历", "items": ["来自现代"]},
	{"title": "性格 / 价值观 / 原则", "items": ["愿意学习"]},
	{"title": "能力 / 专长说明", "items": ["现代常识与学习能力"]},
]}, "experiences": []}

func _run() -> void:
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--root="):
			directory = arg.trim_prefix("--root=")
	if not directory.contains("mw015r2"):
		quit(2)
		return
	DirAccess.make_dir_recursive_absolute(directory)
	var runtime := Runtime.new()
	check(runtime.open_current_game(directory.path_join("initial.sqlite")).success, "fresh production runtime")
	check(runtime.commit_world_mutation_durably("setup", "setup", setup()).success, "frozen Game profile")
	var pre := runtime.create_save_point("初始整理之前")
	var stub := Stub.new()
	var worker := Curator.new(runtime, stub)
	root.add_child(worker)
	await frames()
	check(stub.requests.size() == 1 and runtime.conversation.get_durable_accepted_entries().is_empty(), "activation starts initial with zero accepted turns")
	var input: Dictionary = JSON.parse_string(stub.requests[0][1].content)
	check(input.keys() == ["frozen_starting_profile"], "initial input is exactly frozen safe material")
	check(input.frozen_starting_profile == Contract.initial_input(Profile.project_frozen_profile(runtime.world_state)), "binding uses exact normalized model material")
	check(JSON.stringify(input).contains("水壶"), "Program passes possessions to model without semantic filtering")
	for forbidden: String in ["NPC_PRIVATE", "GM_PRIVATE", "HIDDEN_EVOLUTION", "PRIVATE_PLAN", "SOURCE_CURRENT", "raw-secret"]:
		check(not JSON.stringify(input).contains(forbidden), "initial safe input excludes " + forbidden)
	check(runtime.conversation.begin_gm_opening() != null, "opening independent while initial busy")
	runtime.conversation.cancel_generation()
	complete(stub, BASELINE)
	await frames()
	check(SafeView.project_session(runtime).character == BASELINE.character, "rich baseline before opening success")
	check(runtime.conversation.get_durable_accepted_entries().is_empty(), "no synthetic accepted turn")
	check(SafeView.project_session(runtime).important_experiences.is_empty(), "T0 has no milestone")
	var record: Dictionary = runtime.world_state.information_curation.initial.duplicate(true)
	var count := stub.requests.size()
	for index: int in range(10):
		SafeView.project_session(runtime)
	worker.retry_pending()
	await frames()
	check(stub.requests.size() == count, "render/retry successful baseline does not call provider")
	var baseline_save := runtime.create_save_point("基线")
	accept(runtime, "行动", "已接受的叙事")
	await frames()
	var lived := changed("替代原能力", "未来经历")
	complete(stub, lived)
	await frames()
	check(SafeView.project_session(runtime).character == lived.character, "lived replaces and removes baseline groups")
	check(runtime.world_state.information_curation.initial == record, "no second baseline copy")
	accept(runtime, "保持", "继续")
	await frames()
	complete(stub, NO_CHANGE)
	await frames()
	check(SafeView.project_session(runtime).character == lived.character, "null lived retains preceding snapshot")
	var chain: Dictionary = runtime.world_state.information_curation.turns.duplicate(true)
	var without_initial: Dictionary = runtime.world_state.duplicate(true)
	without_initial.information_curation.erase("initial")
	check(runtime.commit_world_mutation_durably("legacy", "legacy", without_initial).success, "legacy owner without initial")
	check(Contract.current_records(runtime.world_state, runtime.conversation.get_durable_accepted_entries()).size() == 2, "legacy turn chain readable")
	worker.retry_pending()
	await frames()
	check(runtime.world_state.information_curation.turns == chain, "reattach preserves every historical ID and parent")
	check(runtime.world_state.information_curation.initial == record and stub.requests.size() == count + 2, "durable exact baseline reuse without provider")
	check(runtime.restore_save_point(baseline_save.save_id).success, "restore baseline snapshot")
	await frames()
	check(SafeView.project_session(runtime).character == BASELINE.character and SafeView.project_session(runtime).important_experiences.is_empty(), "Restore removes future lived material")
	# 关闭 curator 后 Restore，再关闭 Runtime，证明重新打开不是依赖内存缓存。
	worker.shutdown()
	worker.queue_free()
	check(runtime.restore_save_point(pre.save_id).success, "restore pre-initial while worker absent")
	runtime.close()
	await frames()
	runtime = Runtime.new()
	check(runtime.open_existing_game(directory.path_join("initial.sqlite")).success, "reopen pre-initial existing Game")
	stub = Stub.new()
	worker = Curator.new(runtime, stub)
	root.add_child(worker)
	await frames()
	check(stub.requests.is_empty(), "reopen finds durable T0 result in displaced node without model")
	check(SafeView.project_session(runtime).character == BASELINE.character and SafeView.project_session(runtime).important_experiences.is_empty(), "reuse imports only baseline, never future owner")
	check(runtime.world_state.information_curation.turns.is_empty(), "future turn records not copied")
	accept(runtime, "重新行动", "新叙事")
	await frames()
	complete(stub, NO_CHANGE)
	await frames()
	runtime.conversation.retry_or_regenerate_latest()
	runtime.conversation.append_delta("替代叙事")
	check(runtime.complete_active_generation_durably().success, "regenerate accepted")
	await frames()
	check(runtime.world_state.information_curation.initial == record, "Regenerate does not invalidate initial")
	complete(stub, NO_CHANGE)
	await frames()
	worker.shutdown()
	worker.queue_free()
	runtime.close()
	await frames()
	await initial_failures()
	print("MW-015 R2 checks=%d failures=%d" % [checks, failures])
	quit(0 if failures == 0 else 1)

func initial_failures() -> void:
	var runtime := RejectingRuntime.new()
	check(runtime.open_current_game(directory.path_join("failures.sqlite")).success, "failure runtime")
	check(runtime.commit_world_mutation_durably("setup", "setup", setup()).success, "failure frozen profile")
	var save := runtime.create_save_point("在途")
	var stub := Stub.new()
	var worker := Curator.new(runtime, stub)
	root.add_child(worker)
	await frames()
	var before: Dictionary = runtime.world_state.duplicate(true)
	complete(stub, changed("角色", "静态传记不允许产生经历"))
	await frames()
	check(runtime.world_state == before and worker.last_result.status == "invalid_initial_result", "initial milestones rejected as lifecycle violation")
	check(runtime.conversation.begin_turn("前台不受阻") != null, "invalid initial does not gate player")
	runtime.conversation.cancel_generation()
	worker.retry_pending()
	await frames()
	stub.simulate_failed()
	await frames()
	check(runtime.world_state == before and not stub.busy, "provider failure bounded and zero mutation")
	worker.retry_pending()
	await frames()
	runtime.reject_curation = true
	complete(stub, BASELINE)
	await frames()
	check(runtime.world_state == before and worker.last_result.status == "persistence_failure", "failed commit never publishes initial")
	runtime.reject_curation = false
	worker.retry_pending()
	await frames()
	var moved: Dictionary = runtime.world_state.duplicate(true)
	moved["test_marker"] = true
	check(runtime.commit_world_mutation_durably("advance", "advance", moved).success, "advance before in-flight Restore")
	check(runtime.restore_save_point(save.save_id).success, "Restore cancels in-flight initial")
	stub.simulate_delta(JSON.stringify(BASELINE))
	stub.simulate_completed()
	check(runtime.world_state == before, "old response cannot cross Restore epoch")
	await frames()
	check(stub.busy, "Restore without durable baseline eligible again")
	complete(stub, BASELINE)
	await frames()
	var changed_profile := setup()
	changed_profile.player_character.source_projection.player_profile.summary = "另一个冻结起点"
	changed_profile["information_curation"] = runtime.world_state.information_curation.duplicate(true)
	check(Contract.current_initial(changed_profile, Profile.project_frozen_profile(changed_profile)).is_empty(), "changed frozen binding rejects prior baseline")
	worker.shutdown()
	worker.queue_free()
	runtime.close()
	await frames()
	var missing := Runtime.new()
	check(missing.open_current_game(directory.path_join("missing.sqlite")).success, "legacy missing profile")
	var absent_stub := Stub.new()
	var absent := Curator.new(missing, absent_stub)
	root.add_child(absent)
	await frames()
	check(absent_stub.requests.is_empty() and absent.last_result.status == "initial_profile_unavailable", "incompatible Game reported without Source backfill")
	absent.shutdown()
	absent.queue_free()
	missing.close()
	await frames()
